---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by User.
--- DateTime: 21.04.2022 9:11
---

local Class = require('lib/Class')
local AShape = Class:extended({ class = "AbstractClass AShape" })

AShape.voxelType = {
    internal = 'I',
    external = 'E',
    surface = 'S'
}

function AShape:new(initTable)
    local instance = self.super:new()
    return self:extendedInstance(instance)
end

function AShape:set(initTable)
    self:noImplError('set(initTable)')
end

function AShape:getVoxelGlobal(x,y,z)
    self:noImplError('getVoxelGlobal(x,y,z)')
end

function AShape:getVoxelLocal(x,y,z)
    self:noImplError('getVoxelLocal(x,y,z)')
end

return AShape