---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SZS.
--- DateTime: 23.04.2022 21:32
---
local Class = require('libEx/Class')


local NativeComputer = require('computer')
local NativeRobotApi = require("robot")
local Position = require('libEx/Position')

NativeRobotApi.class = "Class NativeRobotApi"
NativeComputer.class = "Class NativeComputer"

---@class RobotExtendedApi : NativeRobotApi @extended native OC API robot, computer
local RobotExtendedApi = Class:extended(NativeComputer):extended(NativeRobotApi):extended({
    class = "Class RobotExtendedApi"
})


---@type fun(init:table):RobotExtendedApi
function RobotExtendedApi:new(initTable)
    local instance = self.super:new()
    return self:extendedInstance(instance):init(initTable)
end

-- startPosition {0,0,0,0} x,y,z,r / r : Position.side
---@type fun(init:table):RobotExtendedApi
function RobotExtendedApi:init(initTable)
    local error = ":init(initTable) initTable."
    ---@type Position
    self.position = Position:new(table.unpack(
        self:assert(initTable.startPosition, error..".startPosition is nil")
    ))    
    ---@type AInventoryManager
    self.inventoryManager = self:assert(initTable.inventoryManager, "initTable.inventoryManager is nil"):init(self.super)
    ---@type ABaseStation
    self.baseStation = self:assert(initTable.baseStation, "initTable.baseStation is nil")
    return self
end

---@type fun(removeObstacle:boolean, tries:number): boolean, string
function RobotExtendedApi:forward( removeObstacle, tries)
    self:baseMove(self.super.forward(), ":forward()", self.swing, self.position.stepForward, removeObstacle, tries)
end

-- todo self.moveImpossibleHendler is plug
function RobotExtendedApi:back( removeObstacle, tries)
    self:baseMove(self.super.back(), ":back()", self.moveImpossibleHendler, self.position.stepBack, removeObstacle, tries)
end

function RobotExtendedApi:up( removeObstacle, tries)
    self:baseMove(self.super.up(), ":up()", self.swingUp, self.position.stepUp, removeObstacle, tries)
end

function RobotExtendedApi:down( removeObstacle, tries)
    self:baseMove(self.super.down(), ":down()", self.swingDown, self.position.stepDown, removeObstacle, tries)
end

function RobotExtendedApi:swing()
    return self:baseSwing(self.super.swing, ":swing()")
end

function RobotExtendedApi:swingUp()
    return self:baseSwing(self.super.swingUp, ":swingUp()")
end

function RobotExtendedApi:swingDown()
    return self:baseSwing(self.super.swingDown, ":swingDown()")
end

---@param funcName string @ up, down, forward, back
---@param status boolean
---@param error string @ impossible move, not enough energy or robot.detect would return. https://ocdoc.cil.li/api:robot
---@type fun(funcName:string, status:boolean, error:string): boolean, string
function RobotExtendedApi:moveImpossibleHendler(funcName, status, error)
    self:error(tostring(funcName) .. " move is impossible")
end

function RobotExtendedApi:swingImpossibleHendler(funcName, status, message)
    self:error(":" .. funcName .. " " .. message .. " is impossible")
end

---@private
function RobotExtendedApi:baseMove(nativeMoveFunc, moveFuncName, swingFunc, movePositionFunc, removeObstacle, tries)
    local status, error = nativeMoveFunc()
    if status then
        -- self.position:stepForward()
        movePositionFunc(self.position)
        return status, error
    end
    if removeObstacle then
        while not tries or tries > 0 do
            -- self:swing()
            swingFunc(self)
            status, error = nativeMoveFunc()
            if status then
                -- self.position:stepForward()
                movePositionFunc(self.position)
                return status, error
            end
            if tries then
                tries = tries - 1
            end
        end
    end
    return self:moveImpossibleHendler(moveFuncName, status, error)
end

---@private
function RobotExtendedApi:baseSwing(nativeSwingFunc, funcName)
    if not self.inventoryManager:checkSelectedTool() then
        --tool service
    end
    local status, message = nativeSwingFunc()
    if not status then
        if message ~= 'entity' then           
            for tool in self.inventoryManager:nextToolToRemoveBlock() do
                status, message = nativeSwingFunc()
                if status then
                    break
                end
            end
            self.inventoryManager:selectDefaultTool()
            if not status then
                return self:swingImpossibleHendler(funcName, status, error)
            end
        end
    end
end

return RobotExtendedApi
