---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SZS.
--- DateTime: 16.04.2022 13:23
---

function tableViewer(object, offset)
  if type(object) == 'table' then
    print(offset..tostring(object))
    for key, value in pairs(object) do
      print(offset, key, value)
      if type(value) == 'table' then
        tableViewer(value, offset..' ')
      end
    end
  else
    print(offset..tostring(object))
  end
end