---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SZS.
--- DateTime: 19.04.2022 15:13
---

function packPosition(cordX, cordY, cordZ, _direction)
    return {x = cordX, y = cordY, z = cordZ, direction = _direction}
end