---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by SZS.
--- DateTime: 16.04.2022 12:47
---

local robot = {}

function robot.detectUp()
    -- return boolean, string
end

--[[function robot.getLightColor()
    -- undefined
end]]

---@param slot number
---@param count number
---@return boolean
function robot.transferTo(slot, count)
    -- slot:number
    -- [count:number]

    -- return boolean
end

function robot.drain()

end

function robot.back()

end

function robot.detect()

end

function robot.down()

end

function robot.count()

end

function robot.space()

end

function robot.dropDown()

end

function robot.placeDown()

end

function robot.drainUp()

end

function robot.suckUp()

end

function robot.fillDown()

end

function robot.forward()

end

function robot.drop()

end

function robot.select()

end

function robot.fillUp()

end

function robot.up()

end

function robot.turnRight()

end

function robot.useDown()

end

function robot.use()

end

function robot.compareUp()

end

function robot.drainDown()

end

function robot.tankLevel()

end

function robot.compareTo()

end

function robot.compare()

end

function robot.dropUp()

end

function robot.compareDown()

end

function robot.inventorySize()

end

function robot.level()

end

function robot.compareFluid()

end

function robot.compareFluidTo()

end

function robot.transferFluidTo()

end

function robot.tankSpace()

end

function robot.name()

end

function robot.place()

end

function robot.turnAround()

end

function robot.swingDown()

end

function robot.suckDown()

end

function robot.turnLeft()

end

function robot.placeUp()

end

function robot.detectDown()

end

function robot.setLightColor()

end

function robot.swing()

end

function robot.useUp()

end

function robot.compareFluidDown()

end

function robot.compareFluidUp()

end

function robot.durability()

end

function robot.tankCount()

end

function robot.fill()

end

function robot.swingUp()

end

function robot.selectTank()

end

function robot.suck()

end

return robot